---
title: "EDA"
output: pdf_document
---

```{r echo=FALSE, warning=FALSE, results=FALSE, message=FALSE}
library(tidyverse)
library(data.table)
```

```{r}
categorical_columns = c('d_ira', 'cor', 'has', 'dm', 'icc',
                        'asma_dpoc', 'hiv', 'ca_ativo', 'avc', 
                        'dvp', 'drogadicao', 'ventilacao_mecanica',
                        'diureticos', 'vasopressina', 'israa',
                        'causa_ira', 'kdigo', 'criterio_ira',
                        'pos_operatorio', 'mortalidade_intra_hospitalar')

daily_columns = c('diurese',
                  'bh',
                  'sofa',
                  'su',
                  'scr',
                  'sna',
                  'sk',
                  'sosm',
                  'uu',
                  'ucr',
                  'una',
                  'uk',
                  'volume_urinario',
                  'uvu24h',
                  'feu',
                  'uu_ucr',
                  'una_ucr',
                  'uvna24h',
                  'uosm',
                  'uosm_estimada',
                  'una+uk',
                  'uu_su',
                  'fena',
                  'fek',
                  'su_scr',
                  'delta_scr')
```


```{r}
df = readRDS('./data/processed_data_mean_v2.rds') %>%
    mutate_at(categorical_columns, list(~factor(.)))

columns = colnames(df)

head(df)
```


```{r}
for(column in categorical_columns){
    p = df %>%
        group_by(!!sym(column)) %>%
        summarise(cnt = n()) %>%
        ggplot(aes(x=!!sym(column), y=cnt)) + 
            geom_col(fill='firebrick', alpha=0.7) + 
            labs(title=paste('Contagem da vari치vel: ', column))
    print(p)
}
```


```{r}
for(column in categorical_columns[categorical_columns != 'D_IRA']){
    p = df %>%
        group_by(!!sym(column), ira) %>%
        summarise(cnt = n()) %>%
        ggplot(aes(x=!!sym(column), y=cnt,
                   color=ira, fill=ira)) + 
            geom_col(alpha=0.7, position='dodge') + 
            labs(title=paste('Contagem da vari치vel: ', column))
    print(p)
}
```


```{r}
for(column in categorical_columns[categorical_columns != 'D_IRA']){
    p = df %>%
        group_by(!!sym(column), ira) %>%
        summarise(cnt = n()) %>%
        ungroup %>%
        mutate(pct = cnt / sum(cnt)) %>%
        ggplot(aes(x=!!sym(column), y=pct,
                   color=ira, fill=ira)) + 
            geom_col(alpha=0.7, position='dodge') 
            # labs(title=paste('Contagem da vari치vel: ', column))
    print(p)
}
```


```{r}
for(column in categorical_columns[categorical_columns != 'd_ira']){
    p = df %>%
        group_by(!!sym(column), kdigo_agrupado) %>%
        summarise(cnt = n()) %>%
        ggplot(aes(x = !!sym(column), y = cnt,
                   color = kdigo_agrupado, 
                   fill = kdigo_agrupado)) + 
            geom_col(alpha = 0.7, position ='dodge') + 
            labs(title = paste('Contagem da vari치vel: ', column))
    print(p)
}
```


```{r}
df[rowSums(is.na(df %>% select(-criterio_ira))) > 0,]
```

```{r}
df %>%
    select(uosm, uosm_estimada) %>%
    ggplot(aes(x = uosm_estimada, y = uosm)) + 
        geom_point() + 
        geom_abline(intercept = 0, slope = 1,
                    linetype = 2, color = 'red')
```

```{r}

```

