---
title: "Modelagem"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf')
```

```{r echo=FALSE, warning=FALSE, results=FALSE, message=FALSE}
library(tidyverse)
library(broom)
library(xtable)
library(kableExtra)
library(gridExtra)
library(yaml)
library(caret)
library(formula.tools)
```

```{r echo = F, results = F}
constants = yaml.load_file("constants.yaml")

categorical_columns = constants$categorical_columns

daily_columns = constants$daily_columns

numerical_columns = constants$numerical_columns

solutos_columns = constants$solutos_columns

all_columns = c(numerical_columns, categorical_columns)

original_columns = constants$original_columns

derived_columns = setdiff(daily_columns, original_columns)
```


```{r echo = F, results = F}
df = readRDS('./data/processed_data_mean_v2.rds') %>%
    mutate_at(categorical_columns, list(~factor(.)))
```

```{r echo = FALSE}
selected_columns_yaml = yaml.load_file("selected_columns.yaml")

selected_camila_numerical_columns = selected_columns_yaml$selected_camila_columns

selected_numerical_columns = selected_columns_yaml$selected_numerical_columns

selected_categorical_columns = selected_columns_yaml$selected_categorical_columns

drop_scr = TRUE

target = "ira"
```

```{r echo = FALSE}
if (drop_scr){
  selected_camila_numerical_columns = setdiff(selected_camila_numerical_columns, 'scr')
  selected_numerical_columns = setdiff(selected_numerical_columns, 'scr')
}
```

```{r echo = FALSE}
gilberto_diagnostics = function(fit.model){
  X <- model.matrix(fit.model)
  n <- nrow(X)
  p <- ncol(X)
  w <- fit.model$weights
  W <- diag(w)
  H <- solve(t(X)%*%W%*%X)
  H <- sqrt(W)%*%X%*%H%*%t(X)%*%sqrt(W)
  h <- diag(H)
  ts <- resid(fit.model,type="pearson")/sqrt(1-h)
  td <- resid(fit.model,type="deviance")/sqrt(1-h)
  di <- (h/(1-h))*(ts^2)
  a <- max(td)
  b <- min(td)
  
  p1 = ggplot(data.frame(fitted = fitted(fit.model), h = h)) +
    geom_point(aes(x = fitted, y = h)) + 
    labs(x = "Valor Ajustado", y = "Medida h") +
    theme_bw()
  
  #identify(fitted(fit.model), h, n=1)
  
  p2 = ggplot(data.frame(di = di, index = seq(1, length(di)))) +
    geom_point(aes(x = index, y = di)) + 
    labs(x = "Índice", y = "Distância de Cook") +
    theme_bw()
  
  #identify(di, n=1)
  
  p3 = ggplot(data.frame(td = td, index = seq(1, length(td))),
              aes(x = index, y = td)) +
    geom_point() + 
    labs(x = "Índice", y = "Resíduo Componente do Desvio") +
    geom_hline(yintercept = 2, linetype = 'dotted') + 
    geom_hline(yintercept = -2, linetype = 'dotted') + 
    theme_bw()
  
  #identify(td, n=1)
  
  p4 = ggplot(data.frame(fitted = fitted(fit.model), td = td)) +
    geom_point(aes(x = fitted, y = td)) + 
    labs(x = "Valor Ajustado", y = "Resíduo Componente do Desvio") +
    theme_bw()
  
  #identify(fitted(fit.model), td, n=1)
  
  print(p1)
  print(p2)
  print(p3)
  print(p4)
}

envelope_simulado = function(model, tol = 1e-22){
  X <- model.matrix(model)
  n <- nrow(X)
  p <- ncol(X)
  w <- model$weights
  W <- diag(w)
  H <- solve(t(X)%*%W%*%X, tol = tol)
  H <- sqrt(W)%*%X%*%H%*%t(X)%*%sqrt(W)
  h <- diag(H)
  td <- resid(model,type="deviance") / sqrt(1 - h)
  e <- matrix(0, n, 100)
  #
  for(i in 1:100){
    dif <- runif(n) - fitted(model)
    dif[dif >= 0 ] <- 0
    dif[dif < 0] <- 1
    nresp <- dif
    fit <- glm(nresp ~ X, family = binomial)
    w <- fit$weights
    W <- diag(w)
    H <- solve(t(X)%*%W%*%X, tol = tol)
    H <- sqrt(W)%*%X%*%H%*%t(X)%*%sqrt(W)
    h <- diag(H)
    e[,i] <- sort(resid(fit, type = "deviance") / sqrt(1 - h))
  }
  #
  e1 <- numeric(n)
  e2 <- numeric(n)
  #
  for(i in 1:n){
    eo <- sort(e[i,])
    e1[i] <- (eo[2] + eo[3]) / 2
    e2[i] <- (eo[97] + eo[98]) / 2
  }

  med <- apply(e, 1, mean)
  
  p = ggplot(data.frame(td = td,
                    e1 = e1, 
                    e2 = e2,
                    med = med)) + 
    stat_qq(aes(sample = td)) + 
    stat_qq(aes(sample = e1), 
            geom = 'line') +
    stat_qq(aes(sample = e2), 
            geom = 'line') +
    stat_qq(aes(sample = med), 
            geom = 'line',
            linetype = 'dotted') +
    labs(x = "Percentil da N(0,1)", y = "Componente do Desvio") +
    theme_bw()
  
  print(p)
}
```

```{r echo = F, results = F}
fit_model = function(df, numerical_features, categorical_features, target, include_interaction = FALSE){
  factor_formula = paste(sprintf("factor(%s)",
                                 categorical_features),
                         collapse = " + ") 
  numerical_formula = paste(numerical_features, collapse = " + ")
  interaction_formula = ""

  if('causa_ira' %in% c(categorical_features, numerical_features) & include_interaction){
    solutos_features = intersect(numerical_features, solutos_columns) 
    if(length(solutos_features > 0)){
      interaction_formula = paste(paste0("factor(causa_ira) : ",
                                         solutos_features),
                                  collapse = " + ") 
    }
  }
  
  formulas_vetor = c(factor_formula, numerical_formula, interaction_formula)
  
  formula_string = sprintf("%s ~ %s", target, 
                           paste(formulas_vetor[formulas_vetor!=""], collapse = " + "))
  formula = formula_string %>% as.formula
  
  model <- glm(formula, data = df, family = "binomial")
  return(model)
}

fit_multiple_models = function(df, numerical_features, categorical_features,
                               target, include_interaction=FALSE, trace=0){
  full_model <- fit_model(df, numerical_features, categorical_features,
                          target, include_interaction=include_interaction)
  
  null_model = glm(ira ~ 1, data = df, 
                   family = "binomial")
  
  backwards = step(full_model, trace = trace)
  
  forwards = step(null_model,
                  scope = list(lower = formula(null_model),
                               upper = formula(full_model)),
                  direction = "forward", trace = trace)
  
  stepwise = step(null_model, 
                  list(lower = formula(null_model),
                       upper = formula(full_model)),
                  direction = "both", trace = trace)
  
  features_union = c(all.vars(backwards$formula[-2]), 
                     all.vars(forwards$formula[-2]),
                     all.vars(stepwise$formula[-2])) %>%
    unique

  features_intersection = intersect(intersect(all.vars(backwards$formula[-2]), 
                                              all.vars(forwards$formula[-2])),
                                    all.vars(stepwise$formula[-2]))
  
  union_model = fit_model(df, features_union, c(),
                          target, include_interaction = include_interaction)
  intersection_model = fit_model(df, features_intersection, c(),
                                 target, include_interaction = include_interaction)
  
  return(list("Full model" = full_model,
              "Backwards" = backwards,
              "Forwards" = forwards,
              "Stepwise" = stepwise,
              "Union model" = union_model,
              "Intersection model" = intersection_model))
  
}

model_summary = function(df, model){
  columns = all.vars(model$formula[-2])
  
  options(xtable.comment = FALSE)

  model %>% 
    tidy() %>% 
    niceFormatting(caption = "Model summary") %>%
    print
  
  model %>% 
    glance() %>% 
    niceFormatting(caption = "Model details") %>%
    print
  
  confint.default(model) %>% 
    exp %>%
    as_tibble(rownames = 'variável') %>%
    mutate(estimativa = exp(model$coefficients)) %>%
    niceFormatting(caption = "Confidence intervals") %>%
    print
  
  if (length(coef(model)) - 1 > 1){
    car::vif(model) %>%
      niceFormatting(caption = "Variance Inflation Factor") %>%
      print
  }
  
  library(pROC)
  
  df$prob = predict(model, type = "response")
  g = roc(ira ~ prob, data = df, auc=TRUE)
  confusion = coords(g, x = "best", best.method="youden",
                     ret = c("threshold", "specificity", "sensitivity", "fpr"))
  confusion %>% 
    niceFormatting(caption = "Classifier metrics") %>%
    print
  
  p = ggroc(g, legacy.axes = TRUE)+
    geom_point(aes(x = 1 - confusion$specificity, y=confusion$sensitivity),
               colour="blue", size=5) +
    geom_abline(slope = 1, intercept=0, linetype="longdash") + 
    labs(subtitle = paste("AUC:", round(g$auc, 3)))
  
  print(p)
}

model_diagnostics = function(df, model, run_envelope = FALSE){
  
  gilberto_diagnostics(model)
  
  if (run_envelope) envelope_simulado(model)
  
  probabilities <- predict(model, type = "response")
  columns = intersect(all.vars(model$formula[-2]), numerical_columns)
  
  df_2 = df %>%
    dplyr::select(all_of(columns)) %>%
    mutate(logit = log(probabilities/(1-probabilities))) %>%
    gather(key = "predictors", value = "predictor.value", -logit)
  
  p1 = ggplot(df_2, aes(logit, predictor.value))+
    geom_point(size = 0.5, alpha = 0.5) +
    geom_smooth(method = "loess") + 
    theme_bw() + 
    facet_wrap(~ predictors, scales = "free_y", ncol = 2)
  
  model.data <- augment(model) %>% 
    mutate(index = 1:n()) 

  p2 = ggplot(model.data, aes(index, .std.resid)) + 
    geom_point(aes(color = ira), alpha = .5) +
    theme_bw()
  
  print(p1)
}


niceFormatting = function(df, caption=""){
  df %>%
    kbl(booktabs = T, longtable = T, caption = caption, digits = 3) %>%
    kable_styling(latex_options = c("striped", "HOLD_position", "repeat_header"))
}

model_selection = function(df, numerical_columns, categorical_columns,
                           target, trace = 0, include_interaction = FALSE){
  
  fitted_models = fit_multiple_models(df,
                                      numerical_columns,
                                      categorical_columns, 
                                      target, 
                                      include_interaction = include_interaction, 
                                      trace = trace)
  
  for (model in names(fitted_models)){
    cat("### ", model, "\n")
  
    model_summary(df, fitted_models[[model]])
    
    if (!model %in% c('Full model', 'Union model')) {
      model_diagnostics(df, fitted_models[[model]], run_envelope = TRUE)
    } else {
    model_diagnostics(df, fitted_models[[model]])
    }
    
    cat("\n")
    cat("\n")
    cat("\\newpage")
  }
  return(fitted_models)
}
```

# With pacient 34


```{r results='asis', echo=F, message=F, warning=FALSE, fig.height=4, fig.width=7}
cat(paste("## Camila Variables \n"))

# step(camila_models$`Full model`, trace = 1)
# all.vars(camila_models$Backwards$formula)
# model = camila_models$Forwards
# gilberto_diagnostics(model)
# model_summary(df, model)
# model_diagnostics(df, model)
# envelope_simulado(model)

camila_models = model_selection(df,
                                selected_camila_numerical_columns,
                                selected_categorical_columns,
                                target, 
                                include_interaction = TRUE)
```


```{r results='asis', echo=F, message=F, warning=FALSE, fig.height=4, fig.width=7}
cat(paste("## Selected Variables \n"))

selected_models = model_selection(df,
                                  selected_numerical_columns,
                                  selected_categorical_columns,
                                  target, 
                                  include_interaction = FALSE)
```


```{r echo = FALSE, warning= FALSE}
transpose_df <- function(df) {
  t_df <- data.table::transpose(df)
  colnames(t_df) <- rownames(df)
  rownames(t_df) <- colnames(df)
  t_df <- t_df %>%
    tibble::rownames_to_column(.data = .) %>%
    tibble::as_tibble(.)
  return(t_df)
}

df_35 = df %>%
  mutate(row_number = row_number()) %>%
  filter(row_number == 35)

transpose_df(df_35) %>%
  niceFormatting(caption = "Paciente 35")
```

# Without pacient 34

```{r echo=FALSE}
df = df %>%
  mutate(row_number = row_number()) %>%
  filter(row_number != 35)
```


```{r results='asis', echo=F, message=F, warning=FALSE, fig.height=4, fig.width=7}
cat(paste("## Camila Variables \n"))

camila_models = model_selection(df,
                                selected_camila_numerical_columns,
                                selected_categorical_columns,
                                target, 
                                include_interaction = TRUE)
```


```{r results='asis', echo=F, message=F, warning=FALSE, fig.height=4, fig.width=7}
cat(paste("## Selected Variables \n"))

selected_models = model_selection(df,
                                  selected_numerical_columns,
                                  selected_categorical_columns,
                                  target, 
                                  include_interaction = FALSE)
```

# LOOCV

```{r echo = FALSE}
loocv = function(df, formula){
  cat(sprintf("## %s \n", as.character(formula)))
  
  train.control <- trainControl(method = "LOOCV",
                                summaryFunction = twoClassSummary,
                                classProbs=T,
                                savePredictions = T)

  df_cv = df %>% 
    mutate(ira = if_else(ira == 0, "no", "yes"))
  
  model <- train(formula, 
                 data = df_cv,
                 method = "glm",
                 family = "binomial",
                 trControl = train.control,
                 metric = "Sens", 
                 maximize = TRUE)
  
  g = roc(obs ~ yes, data = model$pred, auc=TRUE)
  
  youden = coords(g, x = 'best', best.method="youden",
                  ret = c("threshold", "specificity", "sensitivity"))
  
  confusion = coords(g,
                     ret = c("threshold",
                             "specificity",
                             "sensitivity",
                             "fpr"))
  
  youden_index = confusion %>% 
    mutate(index = row_number()) %>%
    filter(threshold == youden$threshold) %>%
    .$index
  
  confusion %>% 
    niceFormatting(caption = sprintf("Youden threshold = %.3f", youden$threshold)) %>%
    row_spec(youden_index, bold = T, color = "#D7261E") %>%
    print
  
  p = ggroc(g, legacy.axes = TRUE)+
    geom_point(aes(x = 1 - youden$specificity, 
                   y = youden$sensitivity),
               colour="blue",
               alpha = 0.1,
               size=3) +
    geom_abline(slope = 1, intercept=0, linetype="longdash") + 
    labs(subtitle = paste("AUC:", round(g$auc, 3)))
  
  print(p)
}
```


```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
loocv(df, ira ~ sofa + scr_basal)
```

