---
title: "Tabelas"
output: pdf_document
header-includes:
    - \usepackage{caption}
mainfont: Arial
sansfont: Arial
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf', echo=TRUE, message = FALSE, warning = FALSE)
```

# Bibliotecas

```{r results=FALSE}
library(tidyverse)
library(data.table)
library(yaml)
library(kableExtra)

options(OutDec= ",")
```

# Funções auxiliares

```{r}
paste_matrix <- function(...,sep = " ",collapse = NULL){
    n <- max(sapply(list(...),nrow))
    p <- max(sapply(list(...),ncol))

    matrix(paste(...,sep = sep,collapse = collapse),n,p)
}

percent = function(x) paste0("(", lapply(x, as.character), "%)")

addpercentage = function(df){
  x = df %>%
    prop.table(margin = 2) %>%
    addmargins(FUN = list(Total = sum), quiet = TRUE) %>%
    round(2) * 100
  
  x[, ncol(x)] = " " 
  x[, -(ncol(x))] = lapply(x[, -(ncol(x))], percent)
  
  y = matrix(x, nrow = nrow(df) + 1)
  
  df = df %>%
    addmargins(FUN = list(Total = sum), quiet = TRUE)
  
  df_final = paste_matrix(df, y)
  rownames(df_final) = rownames(df)
  colnames(df_final) = colnames(df)
  return(df_final)
}
```


# Carregando os dados

```{r}
constants = yaml.load_file("constants.yaml")

categorical_columns = constants$categorical_columns
numerical_columns = constants$numerical_columns
soluto_columns = constants$solutos_columns

daily_columns = constants$daily_columns
```

```{r}
df = readRDS('./data/dados_processados.rds') %>%
    mutate_at(categorical_columns, list(~factor(.))) %>%
    mutate(ira_nome = if_else(ira == 1, "Sim", "Não"),
           causa_ira_nome = case_when(causa_ira == 0 ~ "Nefrotoxicidade",
                                      causa_ira == 1 ~ "Sepse",
                                      causa_ira == 2 ~ "Isquemia"))

df_names = readxl::read_excel('./data/Nomes das variaveis.xlsx') %>%
  mutate(variavel = tolower(variavel),
         nome = coalesce(nome, variavel)) %>%
  select(nome, variavel)
```

# Tabelas

\captionsetup[table]{labelformat=empty}

## Variáveis numéricas

### Solutos 

```{r results = 'asis'}
i = 1
for (column in soluto_columns){
  
  temp_total_df = df %>%
    group_by(ira_nome) %>%
    summarise(`N` = n(),
              `Média` = mean(!!sym(column), na.rm = T),
              `Desvio Padrão` = sd(!!sym(column), na.rm = T),
              `Mínimo` = min(!!sym(column), na.rm = T),
              `Mediana` = median(!!sym(column), na.rm = T),
              `Máximo` = max(!!sym(column), na.rm = T)) %>%
    ungroup %>%
    mutate(causa_ira_nome = 'Total') %>%
    rename(`Causa da IRA` = causa_ira_nome,
           `IRA` = ira_nome)
  
  nome_variavel = df_names %>% filter(variavel == column) %>% .$nome %>% tolower
  nome_variavel = ifelse(nome_variavel %in% c('imc', 'sofa', 'saps3', 'hiv'), 
                         toupper(nome_variavel),
                         nome_variavel)
  
  caption = sprintf('Tabela A.%d Medidas descritivas para %s por fator de risco', i, 
                    nome_variavel)
  
  df %>%
    group_by(causa_ira_nome, ira_nome) %>%
    summarise(`N` = n(),
              `Média` = mean(!!sym(column), na.rm = T),
              `Desvio Padrão` = sd(!!sym(column), na.rm = T),
              `Mínimo` = min(!!sym(column), na.rm = T),
              `Mediana` = median(!!sym(column), na.rm = T),
              `Máximo` = max(!!sym(column), na.rm = T)) %>%
    ungroup %>%
    rename(`Causa da IRA` = causa_ira_nome,
           `IRA` = ira_nome) %>%
    bind_rows(temp_total_df) %>%
    kbl(align = "c", booktabs = T, digits = 2, format = 'latex',
        caption = caption) %>%
    row_spec(c(1:2, 5:6) - 1, extra_latex_after = "\\rowcolor{gray!6}") %>%
    row_spec(6, hline_after = T) %>%
    row_spec(7:8, bold = T) %>%
    collapse_rows(1, latex_hline = "none") %>%
    kable_styling(latex_options = c("HOLD_position", "repeat_header")) %>%
    print
  
  i = i + 1
}
```

### Resto

```{r results = 'asis'}
for (column in setdiff(numerical_columns, soluto_columns)){
  temp_total_df = df %>%
    summarise(`N` = n(),
              `Média` = mean(!!sym(column), na.rm = T),
              `Desvio Padrão` = sd(!!sym(column), na.rm = T),
              `Mínimo` = min(!!sym(column), na.rm = T),
              `Mediana` = median(!!sym(column), na.rm = T),
              `Máximo` = max(!!sym(column), na.rm = T)) %>%
    ungroup %>%
    mutate(`IRA` = 'Total')
  
  nome_variavel = df_names %>% filter(variavel == column) %>% .$nome %>% tolower
  nome_variavel = ifelse(nome_variavel %in% c('imc', 'saps3'), 
                         toupper(nome_variavel),
                         nome_variavel)
  nome_variavel = ifelse(nome_variavel == 'índice sofa',
                         'índice SOFA', 
                          nome_variavel)
  
  caption = sprintf('Tabela A.%d Medidas descritivas para %s por fator de risco', i, 
                    nome_variavel)
  
  df %>%
    group_by(ira_nome) %>%
    summarise(`N` = n(),
              `Média` = mean(!!sym(column), na.rm = T),
              `Desvio Padrão` = sd(!!sym(column), na.rm = T),
              `Mínimo` = min(!!sym(column), na.rm = T),
              `Mediana` = median(!!sym(column), na.rm = T),
              `Máximo` = max(!!sym(column), na.rm = T)) %>%
    ungroup %>%
    rename(`IRA` = ira_nome) %>%
    bind_rows(temp_total_df) %>%
    kbl(align = "c", booktabs = T, digits = 2, format = 'latex',
        caption = caption) %>%
    row_spec(c(1, 3) - 1, extra_latex_after = "\\rowcolor{gray!6}") %>%
    row_spec(2, hline_after = T) %>%
    row_spec(3, bold = T) %>%
    kable_styling(latex_options = c("HOLD_position", "repeat_header")) %>%
    print
  
  i = i + 1
}
```

## Variáveis categóricas

```{r results = 'asis', message = F, warning = F}

for (column in categorical_columns){
  
  nome_variavel = df_names %>% filter(variavel == column) %>% .$nome %>% tolower
  nome_variavel = ifelse(nome_variavel %in% c('imc', 'saps3', 'kdigo', 'hiv'), 
                         toupper(nome_variavel),
                         nome_variavel)
  
  caption = sprintf('Tabela A.%d Tabela de contingência entre IRA e %s', i, 
                    nome_variavel)
  
  table(df$ira_nome, df[[column]]) %>%
    addpercentage %>%
    kbl(align = "c", booktabs = T, digits = 2, format = 'latex',
        caption = caption) %>%
    row_spec(2, hline_after = T) %>%
    collapse_rows(1, latex_hline = "none") %>%
    add_header_above(c('IRA' = 1, setNames(length(unique(df[[column]])), column))) %>%
    column_spec(length(unique(df[[column]])) + 1, border_right = T) %>%
    kable_styling(latex_options = c("HOLD_position", "repeat_header")) %>%
    print
  i = i + 1
}

```


